### ISSUE TITLE
Provider module/scraper settings keep resetting to default causing no streams found

### ISSUE THREAD

**Issue by oldgranola** [I-A-C/plugin.video.exodusredux#14] opened 2018-11-11 19:13 UTC
Randomly but frequently the >tools>provider settings resets to default thereby losing user inputs for setting up the lambda scraper module. Results in the inability to get movie links. This requires going back and choosing the lambda module and dowloading the module and configuring, then clearing providers. Then after shutting down kodi, we have to go back and do it again. In Gaia there is a setting for saving the settings cache. I don't see it in exodusredux UI but I suspect there is a similar function which is toggled wrong. I am running Kodi 17 on both linux mint 19 and manjaro 18 on various devices. Others on reddit have this issue also on firestick etc.

**Comment by I-A-C** [comment] 2018-11-11 19:36
Do you happen to have Gaia installed?

**Comment by SerpentDrago** [comment] 2018-11-18 14:12
force update redux though the repo. this should fix it

**Comment by 13Clowns** [comment] 2018-11-18 16:30
Duplicate of #21

**Comment by SerpentDrago** [comment] 2018-11-18 17:33
@13Clowns  not a duplicate of that issue , this is the resettting to default issue , not the link almost loads but doesn't issue

**Comment by oldgranola** [comment] 2018-11-18 19:57
SerpentDrago,
forcing update redux seems to have fixed it. Yes I did have some bits of
gaia still there. manually purged completely as I had evidence of coinminer

**Comment by doko-desuka** [comment] 2018-11-19 12:49
I didn't test it, but I think this is the part that keeps resetting:
https://github.com/I-A-C/script.module.exodusredux/blob/master/lib/resources/lib/modules/sources.py#L1173-L1183

Maybe getCondVisibility has weird behavior? I think querying the file system should be safer, seeing if a folder named 'addons/script.module.lambdascrapers' exists, instead of using getCondVisibility.

**Comment by jewbmx** [comment] 2018-11-27 07:46
I might be wrong because im still a noob but could you make the end of that code @doko-desuka  posted be digits instead of the word 'default?

**Comment by SerpentDrago** [comment] 2018-11-27 15:19
Would love a fix for this , still getting reports and issues 

https://old.reddit.com/r/Addons4Kodi/comments/a0s9x7/exodus_redux_keeps_going_back_to_default_scraper/

**Closed** 2019-03-07 20:18 UTC
